# This file can be used to install module depdencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  repositories:
     archive:
       repo: "https://github.com/voxpupuli/puppet-archive.git"
       ref: "3.2.1"
     java:
       repo: "https://github.com/puppetlabs/puppetlabs-java"
       ref: "3.2.0"
     stdlib:
       repo: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
       ref: "5.1.0"
